name: lambox_pharm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_custom_clippers: ^1.1.1
  font_awesome_flutter: ^8.8.1
  flutter_staggered_animations: ^0.1.2
  after_layout: ^1.0.7+2
  flutter_spinkit: ^4.1.2+1

  provider: ^4.3.2+1
  url_encoder: ^0.0.3

  rflutter_alert: ^1.0.3

  modal_progress_hud: ^0.1.3

  cloud_firestore: ^0.14.1+2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
